#!/usr/bin/env bash
set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}✓${NC} $1"; }
info() { echo -e "${CYAN}→${NC} $1"; }
warn() { echo -e "${YELLOW}!${NC} $1"; }
fail() { echo -e "${RED}✗${NC} $1"; exit 1; }

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║     Big Five Fantasy — Local Dev Stack   ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── 1. Docker check ──────────────────────────────────────────────────────────
info "Checking Docker..."
if ! docker info > /dev/null 2>&1; then
  info "Docker not running — launching Docker Desktop..."
  open -a Docker
  echo -n "   Waiting for Docker"
  until docker info > /dev/null 2>&1; do echo -n "."; sleep 2; done
  echo ""
fi
log "Docker is running"

# ── 2. Supabase: reset (wipe + migrate + seed) ────────────────────────────
# The .env file in this project is not standard KEY=VALUE format; rename it
# temporarily so the Supabase CLI doesn't choke on it.
info "Starting Supabase local stack and resetting database..."
[ -f .env ] && mv .env .env.notes
supabase db reset --workdir . 2>&1 | grep -E "(Started|Applying|Seeding|error|Error|✓|✗|FATAL)" || true
[ -f .env.notes ] && mv .env.notes .env
log "Supabase stack running — migrations and seed applied"

# ── 3. Extract local Supabase credentials ─────────────────────────────────
info "Extracting local Supabase credentials..."
[ -f .env ] && mv .env .env.notes
SUPABASE_STATUS=$(supabase status --workdir . --output json 2>/dev/null)
[ -f .env.notes ] && mv .env.notes .env

LOCAL_DB_URL=$(echo "$SUPABASE_STATUS"     | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('DB URL',''))")
LOCAL_ANON_KEY=$(echo "$SUPABASE_STATUS"   | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('anon key',''))")
LOCAL_SERVICE_KEY=$(echo "$SUPABASE_STATUS"| python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('service_role key',''))")
LOCAL_API_URL=$(echo "$SUPABASE_STATUS"    | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('API URL','http://127.0.0.1:54321'))")
LOCAL_STUDIO_URL=$(echo "$SUPABASE_STATUS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('Studio URL','http://127.0.0.1:54323'))")

if [ -z "$LOCAL_DB_URL" ]; then
  LOCAL_DB_URL="postgresql://postgres:postgres@127.0.0.1:54322/postgres"
fi

log "Credentials extracted"

# ── 4. Write .env.local ───────────────────────────────────────────────────
info "Writing .env.local..."
cat > .env.local << EOF
# ── Local Dev — auto-generated by scripts/dev-local.sh ──
NODE_ENV=development
PORT=3001

# Supabase (local)
VITE_SUPABASE_URL=${LOCAL_API_URL}
VITE_SUPABASE_ANON_KEY=${LOCAL_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${LOCAL_SERVICE_KEY}
SUPABASE_DB_URL=${LOCAL_DB_URL}
SUPABASE_DB_PASSWORD=postgres

# API-Football — read from your shell environment; never committed.
# Export API_FOOTBALL_KEY before running (or add it to .env.local by hand) to enable
# live data sync. The local sim framework does not need it.
VITE_API_FOOTBALL_KEY=${API_FOOTBALL_KEY:-}
API_FOOTBALL_KEY=${API_FOOTBALL_KEY:-}
API_FOOTBALL_BASE_URL=https://api-football-v1.p.rapidapi.com
EOF
log ".env.local written"

# ── 5. Install deps if needed ──────────────────────────────────────────────
if [ ! -d "node_modules" ]; then
  info "Installing npm dependencies..."
  npm install --silent
fi

# ── 6. Print summary banner ───────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              ✨  Local Stack Ready                        ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║${NC}  Frontend (open in browser):                             ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}    ${CYAN}http://localhost:3001${NC}                                  ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}                                                          ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}  Supabase Studio:                                        ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}    ${CYAN}${LOCAL_STUDIO_URL}${NC}                          ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}                                                          ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}  Supabase API:                                           ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}    ${CYAN}${LOCAL_API_URL}${NC}                         ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}                                                          ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}  DB:  ${LOCAL_DB_URL}  ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}                                                          ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}  Seed: 21 clubs · 60 players · 25 fixtures · 10 GWs    ${GREEN}║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
info "Starting backend server... (Ctrl+C to stop everything)"
echo ""

# ── 7. Start backend ──────────────────────────────────────────────────────
NODE_ENV=development node --env-file=.env.local --watch server/index.js
