#!/usr/bin/env bash
set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}✓${NC} $1"; }
info() { echo -e "${CYAN}→${NC} $1"; }
warn() { echo -e "${YELLOW}!${NC} $1"; }
fail() { echo -e "${RED}✗${NC} $1"; exit 1; }

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   Big Five Fantasy — Sim Test Harness   ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── 1. Docker check ──────────────────────────────────────────────────────────
info "Checking Docker..."
if ! docker info > /dev/null 2>&1; then
  info "Docker not running — launching Docker Desktop..."
  open -a Docker
  echo -n "   Waiting for Docker"
  until docker info > /dev/null 2>&1; do echo -n "."; sleep 2; done
  echo ""
fi
log "Docker is running"

# ── 2. Supabase: reset (wipe + migrate + seed + seed_sim) ─────────────────
info "Starting Supabase local stack and resetting database..."
[ -f .env ] && mv .env .env.notes
supabase db reset --workdir . 2>&1 | grep -E "(Started|Applying|Seeding|error|Error|✓|✗|FATAL)" || true
[ -f .env.notes ] && mv .env.notes .env
log "Supabase stack running — migrations and sim seed applied"

# ── 3. Extract local Supabase credentials ─────────────────────────────────
info "Extracting local Supabase credentials..."
[ -f .env ] && mv .env .env.notes
SUPABASE_STATUS=$(supabase status --workdir . --output json 2>/dev/null)
[ -f .env.notes ] && mv .env.notes .env

# Supabase CLI JSON keys are uppercase+underscore (ANON_KEY, DB_URL, ...); fall back to
# the older human-readable keys ("anon key", "DB URL") for compatibility with old CLIs.
LOCAL_DB_URL=$(echo "$SUPABASE_STATUS"     | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('DB_URL') or d.get('DB URL') or '')")
LOCAL_ANON_KEY=$(echo "$SUPABASE_STATUS"   | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('ANON_KEY') or d.get('anon key') or '')")
LOCAL_SERVICE_KEY=$(echo "$SUPABASE_STATUS"| python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('SERVICE_ROLE_KEY') or d.get('service_role key') or '')")
LOCAL_API_URL=$(echo "$SUPABASE_STATUS"    | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('API_URL') or d.get('API URL') or 'http://127.0.0.1:54321')")
LOCAL_STUDIO_URL=$(echo "$SUPABASE_STATUS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('STUDIO_URL') or d.get('Studio URL') or 'http://127.0.0.1:54323')")

if [ -z "$LOCAL_DB_URL" ]; then
  LOCAL_DB_URL="postgresql://postgres:postgres@127.0.0.1:54322/postgres"
fi

log "Credentials extracted"

# ── 4. Write .env.local ───────────────────────────────────────────────────
info "Writing .env.local..."
cat > .env.local << EOF
# ── Local Dev — auto-generated by scripts/fb4-test.sh ──
NODE_ENV=development
PORT=3001

# Supabase (local)
VITE_SUPABASE_URL=${LOCAL_API_URL}
VITE_SUPABASE_ANON_KEY=${LOCAL_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${LOCAL_SERVICE_KEY}
SUPABASE_DB_URL=${LOCAL_DB_URL}
SUPABASE_DB_PASSWORD=postgres

# API-Football — read from your shell environment; never committed.
# Export API_FOOTBALL_KEY before running (or add it to .env.local by hand) to enable
# live data sync. The local sim framework does not need it.
VITE_API_FOOTBALL_KEY=${API_FOOTBALL_KEY:-}
API_FOOTBALL_KEY=${API_FOOTBALL_KEY:-}
API_FOOTBALL_BASE_URL=https://api-football-v1.p.rapidapi.com
EOF
log ".env.local written"

# ── 5. Install deps if needed ──────────────────────────────────────────────
if [ ! -d "node_modules" ]; then
  info "Installing backend npm dependencies..."
  npm install --silent
fi
if [ ! -d "web/node_modules" ]; then
  info "Installing frontend (web/) npm dependencies..."
  npm install --silent --prefix web
fi

# ── 6. Print summary banner ───────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              ✨  Sim Test Stack Ready                     ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║${NC}  Frontend (React + Vite, dev panel, HMR):                ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}    ${CYAN}http://localhost:5173${NC}                                  ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}  Backend API:                                            ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}    ${CYAN}http://localhost:3001/api${NC}                              ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}                                                          ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}  Supabase Studio:                                        ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}    ${CYAN}${LOCAL_STUDIO_URL}${NC}                          ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}                                                          ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}  Sim API:  http://localhost:3001/api/dev/state            ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}                                                          ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}  Seed: 8 teams · 4 matchups · sim_state table           ${GREEN}║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}  Add shell alias (run once):${NC}"
echo -e "  alias fb4-test='npm run --prefix $(pwd) fb4-test'"
echo ""
info "Starting backend (:3001) + Vite dev server (:5173)... (Ctrl+C to stop)"
echo ""

# ── 7. Start backend in the background ────────────────────────────────────
# Vite proxies /api -> :3001, and provides HMR (replaces the old livereload).
NODE_ENV=development node --env-file=.env.local --watch server/index.js &
BACKEND_PID=$!
trap 'kill $BACKEND_PID 2>/dev/null; exit 0' EXIT INT TERM

# Give the backend a moment, then open the React app.
( sleep 2 && open "http://localhost:5173" 2>/dev/null ) &

# ── 8. Start Vite dev server in the foreground ────────────────────────────
npm run dev --prefix web
